name: vertex_ai_quickdraw
description: "Firebase Vertex AI Quickdraw Sample"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  firebase_vertexai: ^1.0.1
  flutter_ai_toolkit: ^0.4.2
  flutter_markdown: ^0.7.3+2
  flutter:
    sdk: flutter
  future_builder_ex: ^4.0.0
  gap: ^3.0.1
  go_router: ^14.2.9
  shared_preferences: ^2.3.2
  split_view: ^3.2.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes_default.json
