name: vertex_ai_quickdraw
description: "Firebase Vertex AI Quickdraw Sample"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_vertexai: ^1.0.2
  flutter_ai_toolkit: ^0.6.5
  flutter:
    sdk: flutter
  signature: ^5.5.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
